pvc:
  annotations:
    volume.beta.kubernetes.io/storage-provisioner: rancher.io/local-path
    volume.kubernetes.io/selected-node: kc-onboard-1
    volume.kubernetes.io/storage-provisioner: rancher.io/local-path
  access_mode:
    - "ReadWriteOnce"
  storage_class_name: "local-path"
configmap:
  - map_type: 'no'
    name: test-rnd-configmap22
    values:
      additionalProp1: string1
      additionalProp2: string2
deployment:
  container:
    - configmaps:
        - test-rnd-configmap22
      volume:
        - name: "dummy"
          mount_path: "/test-rakib"
          size: 1Gi
      container_image: nginx:latest #nginx:1.27.0
      container_name: basic-api
      image_pull_policy: Always
      ports:
        - port: 80
          protocol: TCP
      resource:
        limit:
          cpu: 200m
          ram: 400Mi
        request:
          cpu: 200m
          ram: 400Mi
      secrets:
        - secret-test-ns-rnd22
  labels:
    additionalProp1: label1
    additionalProp2: label2
    additionalProp3: label3
  name: test-nginx-rb
  namespace: default
  replica:
    initial_replica: 1
    max_replica: 10
    min_replica: 1
    scale_utilization_cpu: 50
    scale_utilization_ram: 50
  strategy:
    type: canary-not #it should be conditional with canary or blue-green
    max_surge: 10% #only need when canary
    max_unavailable: 1 #only need when canary
kube_version: '1.19'
namespace:
  labels:
    rnd: niloy
  name: test-ns-rnd-22
secret:
  - name: secret-test-ns-rnd22
    values:
      additionalProp1: test-one
      additionalProp2: test-two
ingress:
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  hosts:
    - host: "rollout-test.95.216.201.183.nip.io"
      paths:
        - path: "/"
          port: 80
          path_type: "Prefix"
