apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: {{ .Values.deployment.name }}
  namespace: {{ .Values.deployment.namespace }}
spec:
  template:
    metadata:
      labels:
        app: {{ .Values.deployment.name }}
        {{- range $key, $value := .Values.deployment.labels }}
        {{ $key | quote }}: {{ $value | quote }}
        {{- end }}
  selector:
    matchLabels:
      app: {{ .Values.deployment.name }}
      {{- range $key, $value := .Values.deployment.labels }}
      {{ $key | quote }}: {{ $value | quote }}
      {{- end }}
  replicas: 2
  revisionHistoryLimit: 5
  strategy:
    canary:
{{/*      steps:*/}}
{{/*        - setWeight: 20*/}}
{{/*        - pause: { }*/}}
{{/*        - setWeight: 40*/}}
{{/*        - pause:*/}}
{{/*            duration: 10*/}}
{{/*        - setWeight: 60*/}}
{{/*        - pause:*/}}
{{/*            duration: 10*/}}
{{/*        - setWeight: 80*/}}
{{/*        - pause:*/}}
{{/*            duration: 10*/}}
      stableService: service-{{ .Values.deployment.name }}
      canaryService: service-{{ .Values.deployment.name }}-rollout
      trafficRouting:
        nginx:
          stableIngress: ingress-{{ .Values.deployment.name }}